package com.example.gitmcp.exception;

/**
 * Error codes for Git MCP operations.
 */
public enum ErrorCode {
    REPOSITORY_NOT_FOUND,
    REPOSITORY_ALREADY_EXISTS,
    INVALID_REPOSITORY_STATE,
    AUTHENTICATION_FAILED,
    NETWORK_ERROR,
    INVALID_PARAMETERS,
    OPERATION_FAILED,
    CONCURRENT_MODIFICATION,
    FILE_NOT_FOUND,
    BRANCH_NOT_FOUND,
    UNCOMMITTED_CHANGES,
    NOTHING_TO_COMMIT
}
